### PR TITLE
Add event handling

### PR DESCRIPTION
**Pull request by u39kun**

### CODE REVIEW

**Comment by benjeffery** [comment]
For some reason I didn't get a notification about this. Thanks so much for doing this - will review it later today hopefully.

**Comment by u39kun** [comment]
Thanks @benjeffery 
BTW lib/PlotlyComponent.js was something that I added to my fork so I can directly point npm at it to install from the git repo.  It ended up showing up in this PR by accident.  You can remove that if/when you merge.

**Comment by benjeffery** [comment]
Ok, all merged and released. I've added a note that these event handlers will only be set on initial creation - we could consider fixing this in componentDidUpdate or something similar.
Thanks! Close this PR if you are happy.

**Comment by u39kun** [comment]
Thanks @benjeffery!

**Pull request closed without merging**
